// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: CabelCaUI1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_Arc1;
lv_obj_t *ui_SLBatCC;
lv_obj_t *ui_Label1;
lv_obj_t *ui_SLBatRC;
lv_obj_t *ui_Label2;
lv_obj_t *ui_SpeedValue;
lv_obj_t *ui_SpeedUnit;
lv_obj_t *ui_ProfileLabel;
lv_obj_t *ui_ProfileNR;


// SCREEN: ui_EStopScreen
void ui_EStopScreen_screen_init(void);
lv_obj_t *ui_EStopScreen;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_EStopLabel;


// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t *ui_SettingsScreen;
lv_obj_t *ui_LSettingsU;
void ui_event_Roller2( lv_event_t * e);
lv_obj_t *ui_Roller2;
void ui_event_BTN_GoTo( lv_event_t * e);
lv_obj_t *ui_BTN_GoTo;
lv_obj_t *ui_L_GoTo_SS;


// SCREEN: ui_ContinueScreen
void ui_ContinueScreen_screen_init(void);
lv_obj_t *ui_ContinueScreen;
lv_obj_t *ui_LContinue;
void ui_event_BTNCancelContinue( lv_event_t * e);
lv_obj_t *ui_BTNCancelContinue;
lv_obj_t *ui_L_NO_CS;
void ui_event_BTNContinue( lv_event_t * e);
lv_obj_t *ui_BTNContinue;
lv_obj_t *ui_L_Yes_CS;
lv_obj_t *ui_SPLoading;
lv_obj_t *ui_LLoading;


// SCREEN: ui_InfoScreen
void ui_InfoScreen_screen_init(void);
lv_obj_t *ui_InfoScreen;
lv_obj_t *ui_LSettingsIU;
lv_obj_t *ui_LableIOh;
lv_obj_t *ui_LabelSoVCC;
lv_obj_t *ui_LabelSoVC;
lv_obj_t *ui_LableIohV;
lv_obj_t *ui_LabelSoVCV;
lv_obj_t *ui_LabelSoVCCV;
void ui_event_BTNBackInfo( lv_event_t * e);
lv_obj_t *ui_BTNBackInfo;
lv_obj_t *ui_L_Back_IS;


// SCREEN: ui_MoreScreen
void ui_MoreScreen_screen_init(void);
lv_obj_t *ui_MoreScreen;
lv_obj_t *ui_LSettingsOU;
lv_obj_t *ui_LGimbalS;
lv_obj_t *ui_Dropdown2;
lv_obj_t *ui_LOtherRope;
lv_obj_t *ui_Switch2;
void ui_event_SLRopeL( lv_event_t * e);
lv_obj_t *ui_SLRopeL;
lv_obj_t *ui_LStoplenght;
lv_obj_t *ui_LStoplenghtV;
void ui_event_BTNBackMore( lv_event_t * e);
lv_obj_t *ui_BTNBackMore;
lv_obj_t *ui_L_Back_MS;
lv_obj_t *ui_LRopeLenghV;
lv_obj_t *ui_LRopeLengh;
void ui_event_SLRopeSL( lv_event_t * e);
lv_obj_t *ui_SLRopeSL;


// SCREEN: ui_ProfileScreen
void ui_ProfileScreen_screen_init(void);
lv_obj_t *ui_ProfileScreen;
lv_obj_t *ui_LSettingsOU1;
void ui_event_BTNBackProfile( lv_event_t * e);
lv_obj_t *ui_BTNBackProfile;
lv_obj_t *ui_L_Back_PS;
lv_obj_t *ui_BNTProfileUp;
void ui_event_Label8( lv_event_t * e);
lv_obj_t *ui_Label8;
lv_obj_t *ui_BNTProfileDown;
lv_obj_t *ui_Label9;
lv_obj_t *ui_LSettingsProfileV;
lv_obj_t *ui_LPSpeed;
lv_obj_t *ui_LSpeedV;
lv_obj_t *ui_LDEC;
lv_obj_t *ui_LACC;
lv_obj_t *ui_LSpeedV1;
lv_obj_t *ui_LSpeedV2;
void ui_event_BNTDSp( lv_event_t * e);
lv_obj_t *ui_BNTDSp;
lv_obj_t *ui_Label10;
lv_obj_t *ui_BNTISp;
lv_obj_t *ui_Label11;
lv_obj_t *ui_BNTDDEC;
lv_obj_t *ui_Label12;
lv_obj_t *ui_BNTIDEC;
lv_obj_t *ui_Label13;
lv_obj_t *ui_BNTDACC;
lv_obj_t *ui_Label14;
lv_obj_t *ui_BNTIACC;
lv_obj_t *ui_Label15;
void ui_event_MoreBTN( lv_event_t * e);
lv_obj_t *ui_MoreBTN;
lv_obj_t *ui_L_More_PS;


// SCREEN: ui_BluethoothScreen
void ui_BluethoothScreen_screen_init(void);
lv_obj_t *ui_BluethoothScreen;
lv_obj_t *ui_LSettingsOU2;
void ui_event_MoreBTN1( lv_event_t * e);
lv_obj_t *ui_MoreBTN1;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Roller1;
void ui_event_SelectBTBTN( lv_event_t * e);
lv_obj_t *ui_SelectBTBTN;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Try_Connection;
lv_obj_t *ui_L_TryCon_BT;
lv_obj_t *ui_BT_Conn_Spin;
void ui_event_BTN_OK_BT( lv_event_t * e);
lv_obj_t *ui_BTN_OK_BT;
lv_obj_t *ui_L_OK_BT;
lv_obj_t *ui_Image1;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
      Disable_EStop( e );
}
}
void ui_event_Roller2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Settings_Select( e );
}
}
void ui_event_BTN_GoTo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Go_To_Settings_BTN( e );
}
}
void ui_event_BTNCancelContinue( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
}
}
void ui_event_BTNContinue( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_LContinue, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_BTNCancelContinue, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_BTNContinue, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_SPLoading, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_LLoading, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      BTN_Continue( e );
}
}
void ui_event_BTNBackInfo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
}
}
void ui_event_SLRopeL( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_LRopeLenghV, target, "", "m");
}
}
void ui_event_BTNBackMore( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ProfileScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ProfileScreen_screen_init);
}
}
void ui_event_SLRopeSL( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_LStoplenghtV, target, "", "m");
}
}
void ui_event_BTNBackProfile( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
}
}
void ui_event_Label8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ( e );
}
}
void ui_event_BNTDSp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Inc_Speed( e );
}
}
void ui_event_MoreBTN( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MoreScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MoreScreen_screen_init);
}
}
void ui_event_MoreBTN1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MoreScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MoreScreen_screen_init);
}
}
void ui_event_SelectBTBTN( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Select_BT_BTN( e );
}
}
void ui_event_BTN_OK_BT( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_LContinue, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_BTNCancelContinue, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_BTN_OK_BT, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_SPLoading, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_LLoading, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      BTN_Continue( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainScreen_screen_init();
ui_EStopScreen_screen_init();
ui_SettingsScreen_screen_init();
ui_ContinueScreen_screen_init();
ui_InfoScreen_screen_init();
ui_MoreScreen_screen_init();
ui_ProfileScreen_screen_init();
ui_BluethoothScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
