// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: CabelCaUI1

#ifndef _CABELCAUI1_UI_H
#define _CABELCAUI1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_SLBatCC;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_SLBatRC;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_SpeedValue;
extern lv_obj_t * ui_SpeedUnit;
extern lv_obj_t * ui_ProfileLabel;
extern lv_obj_t * ui_ProfileNR;
// SCREEN: ui_EStopScreen
void ui_EStopScreen_screen_init(void);
extern lv_obj_t * ui_EStopScreen;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_EStopLabel;
// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_LSettingsU;
extern lv_obj_t * ui_Roller2;
// SCREEN: ui_ContinueScreen
void ui_ContinueScreen_screen_init(void);
extern lv_obj_t * ui_ContinueScreen;
extern lv_obj_t * ui_LContinue;
void ui_event_BTNCancelContinue(lv_event_t * e);
extern lv_obj_t * ui_BTNCancelContinue;
extern lv_obj_t * ui_Label5;
void ui_event_BTNContinue(lv_event_t * e);
extern lv_obj_t * ui_BTNContinue;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_SPLoading;
extern lv_obj_t * ui_LLoading;
// SCREEN: ui_InfoScreen
void ui_InfoScreen_screen_init(void);
extern lv_obj_t * ui_InfoScreen;
extern lv_obj_t * ui_LSettingsIU;
extern lv_obj_t * ui_LableIOh;
extern lv_obj_t * ui_LabelSoVCC;
extern lv_obj_t * ui_LabelSoVC;
extern lv_obj_t * ui_LableIohV;
extern lv_obj_t * ui_LabelSoVCV;
extern lv_obj_t * ui_LabelSoVCCV;
void ui_event_BTNBackInfo(lv_event_t * e);
extern lv_obj_t * ui_BTNBackInfo;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_OtherScreen
void ui_OtherScreen_screen_init(void);
extern lv_obj_t * ui_OtherScreen;
extern lv_obj_t * ui_LSettingsOU;
extern lv_obj_t * ui_LGimbalS;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_LOtherRope;
extern lv_obj_t * ui_Switch2;
void ui_event_SLRopeL(lv_event_t * e);
extern lv_obj_t * ui_SLRopeL;
extern lv_obj_t * ui_LStoplenght;
extern lv_obj_t * ui_LStoplenghtV;
void ui_event_BTNBackOther(lv_event_t * e);
extern lv_obj_t * ui_BTNBackOther;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_LRopeLenghV;
extern lv_obj_t * ui_LRopeLengh1;
void ui_event_SLRopeSL(lv_event_t * e);
extern lv_obj_t * ui_SLRopeSL;
// SCREEN: ui_ProfileScreen
void ui_ProfileScreen_screen_init(void);
extern lv_obj_t * ui_ProfileScreen;
extern lv_obj_t * ui_LSettingsOU1;
void ui_event_BTNBackProfile(lv_event_t * e);
extern lv_obj_t * ui_BTNBackProfile;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_BNTProfileUp;
void ui_event_Label8(lv_event_t * e);
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_BNTProfileDown;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_LSettingsProfileV;
extern lv_obj_t * ui_LPSpeed;
extern lv_obj_t * ui_LSpeedV;
extern lv_obj_t * ui_LDEC;
extern lv_obj_t * ui_LACC;
extern lv_obj_t * ui_LSpeedV1;
extern lv_obj_t * ui_LSpeedV2;
void ui_event_BNTDSp(lv_event_t * e);
extern lv_obj_t * ui_BNTDSp;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_BNTISp;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_BNTDDEC;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_BNTIDEC;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_BNTDACC;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_BNTIACC;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
