// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: CabelCaUI1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Disable_EStop(lv_event_t * e);
void Settings_Select(lv_event_t * e);
void Go_To_Settings_BTN(lv_event_t * e);
void BTN_Continue(lv_event_t * e);
void Inc_Speed(lv_event_t * e);
void Select_BT_BTN(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
