// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: CabelCaUI1

#include "ui.h"

void Disable_EStop(lv_event_t * e)
{
	// Your code here
}

void Settings_Select(lv_event_t * e)
{
	// Your code here
}

void Go_To_Settings_BTN(lv_event_t * e)
{
	switch (lv_roller_get_selected(ui_Roller2))
	{
	case 0:
		_ui_screen_change(&ui_ProfileScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, NULL); //Go to Profile
		break;
	case 1:
		_ui_screen_change(&ui_InfoScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, NULL); //Go to Info
		break;
	case 2: 
		_ui_screen_change(&ui_BluethoothScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, NULL); //Go to Bluethooth
		break;
	case 3:
		_ui_screen_change(&ui_ContinueScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, NULL); //Go to Continue Screen
		break;
	case 4:
		
		break;	

	default:
		break;
	}
}

void BTN_Continue(lv_event_t * e)
{
	// Your code here
}

void Inc_Speed(lv_event_t * e)
{
	// Your code here
}

void Select_BT_BTN(lv_event_t * e)
{
	// Your code here
}
