// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: CabelCaUI1

#include "../ui.h"

void ui_BluethoothScreen_screen_init(void)
{
ui_BluethoothScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BluethoothScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BluethoothScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BluethoothScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LSettingsOU2 = lv_label_create(ui_BluethoothScreen);
lv_obj_set_width( ui_LSettingsOU2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LSettingsOU2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LSettingsOU2, 1 );
lv_obj_set_y( ui_LSettingsOU2, -179 );
lv_obj_set_align( ui_LSettingsOU2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LSettingsOU2,"Bluethooth");
lv_obj_set_style_text_color(ui_LSettingsOU2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LSettingsOU2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LSettingsOU2, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MoreBTN1 = lv_btn_create(ui_BluethoothScreen);
lv_obj_set_width( ui_MoreBTN1, 114);
lv_obj_set_height( ui_MoreBTN1, 44);
lv_obj_set_x( ui_MoreBTN1, 3 );
lv_obj_set_y( ui_MoreBTN1, -108 );
lv_obj_set_align( ui_MoreBTN1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MoreBTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MoreBTN1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MoreBTN1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MoreBTN1, lv_color_hex(0x1F60EA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MoreBTN1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_MoreBTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MoreBTN1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MoreBTN1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MoreBTN1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label18 = lv_label_create(ui_MoreBTN1);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, -2 );
lv_obj_set_y( ui_Label18, 2 );
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"Search");

ui_Roller1 = lv_roller_create(ui_BluethoothScreen);
lv_roller_set_options( ui_Roller1, "                                    \n", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller1, 121);
lv_obj_set_width( ui_Roller1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller1, 5 );
lv_obj_set_y( ui_Roller1, 2 );
lv_obj_set_align( ui_Roller1, LV_ALIGN_CENTER );

ui_SelectBTBTN = lv_btn_create(ui_BluethoothScreen);
lv_obj_set_width( ui_SelectBTBTN, 114);
lv_obj_set_height( ui_SelectBTBTN, 44);
lv_obj_set_x( ui_SelectBTBTN, 3 );
lv_obj_set_y( ui_SelectBTBTN, 116 );
lv_obj_set_align( ui_SelectBTBTN, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SelectBTBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SelectBTBTN, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SelectBTBTN, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SelectBTBTN, lv_color_hex(0x00D804), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SelectBTBTN, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SelectBTBTN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SelectBTBTN, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SelectBTBTN, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SelectBTBTN, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label19 = lv_label_create(ui_SelectBTBTN);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label19, -2 );
lv_obj_set_y( ui_Label19, 2 );
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"Select");

ui_Try_Connection = lv_obj_create(ui_BluethoothScreen);
lv_obj_set_width( ui_Try_Connection, 384);
lv_obj_set_height( ui_Try_Connection, 278);
lv_obj_set_x( ui_Try_Connection, 1 );
lv_obj_set_y( ui_Try_Connection, 4 );
lv_obj_set_align( ui_Try_Connection, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Try_Connection, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Try_Connection, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Try_Connection, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Try_Connection, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Try_Connection, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Try_Connection, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_L_TryCon_BT = lv_label_create(ui_Try_Connection);
lv_obj_set_width( ui_L_TryCon_BT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_L_TryCon_BT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_L_TryCon_BT, 10 );
lv_obj_set_y( ui_L_TryCon_BT, -63 );
lv_obj_set_align( ui_L_TryCon_BT, LV_ALIGN_CENTER );
lv_label_set_text(ui_L_TryCon_BT,"Try to connect ");
lv_obj_set_style_text_color(ui_L_TryCon_BT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_L_TryCon_BT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_L_TryCon_BT, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BT_Conn_Spin = lv_spinner_create(ui_Try_Connection,1000,90);
lv_obj_set_width( ui_BT_Conn_Spin, 80);
lv_obj_set_height( ui_BT_Conn_Spin, 61);
lv_obj_set_x( ui_BT_Conn_Spin, 8 );
lv_obj_set_y( ui_BT_Conn_Spin, 61 );
lv_obj_set_align( ui_BT_Conn_Spin, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BT_Conn_Spin, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_BTN_OK_BT = lv_btn_create(ui_Try_Connection);
lv_obj_set_width( ui_BTN_OK_BT, 114);
lv_obj_set_height( ui_BTN_OK_BT, 44);
lv_obj_set_x( ui_BTN_OK_BT, 1 );
lv_obj_set_y( ui_BTN_OK_BT, 56 );
lv_obj_set_align( ui_BTN_OK_BT, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_OK_BT, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTN_OK_BT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_OK_BT, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_OK_BT, lv_color_hex(0x00D804), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_OK_BT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_BTN_OK_BT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BTN_OK_BT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BTN_OK_BT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BTN_OK_BT, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_L_OK_BT = lv_label_create(ui_BTN_OK_BT);
lv_obj_set_width( ui_L_OK_BT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_L_OK_BT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_L_OK_BT, -2 );
lv_obj_set_y( ui_L_OK_BT, 2 );
lv_obj_set_align( ui_L_OK_BT, LV_ALIGN_CENTER );
lv_label_set_text(ui_L_OK_BT,"OK");

ui_Image1 = lv_img_create(ui_BluethoothScreen);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_MoreBTN1, ui_event_MoreBTN1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SelectBTBTN, ui_event_SelectBTBTN, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_OK_BT, ui_event_BTN_OK_BT, LV_EVENT_ALL, NULL);

lv_obj_add_flag(ui_Try_Connection,LV_OBJ_FLAG_HIDDEN);

}
