// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: CabelCaUI1


#include "lvgl.h"
#include "UI/ui.h"

void ui_ContinueScreen_screen_init(void)
{
    ui_ContinueScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ContinueScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContinueScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContinueScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LContinue = lv_label_create(ui_ContinueScreen);
    lv_obj_set_width(ui_LContinue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LContinue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LContinue, 0);
    lv_obj_set_y(ui_LContinue, -47);
    lv_obj_set_align(ui_LContinue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LContinue, "Are you sure you want to continue");
    lv_obj_set_style_text_color(ui_LContinue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LContinue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LContinue, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNCancelContinue = lv_btn_create(ui_ContinueScreen);
    lv_obj_set_width(ui_BTNCancelContinue, 114);
    lv_obj_set_height(ui_BTNCancelContinue, 44);
    lv_obj_set_x(ui_BTNCancelContinue, -103);
    lv_obj_set_y(ui_BTNCancelContinue, 72);
    lv_obj_set_align(ui_BTNCancelContinue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNCancelContinue, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTNCancelContinue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTNCancelContinue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTNCancelContinue, lv_color_hex(0xD8002F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNCancelContinue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTNCancelContinue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTNCancelContinue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BTNCancelContinue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BTNCancelContinue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTNCancelContinue, lv_color_hex(0xD8002F), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BTNCancelContinue, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_BTNCancelContinue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_BTNCancelContinue, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_BTNCancelContinue, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_BTNCancelContinue, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_BTNCancelContinue, lv_color_hex(0xD8002F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BTNCancelContinue, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_BTNCancelContinue, lv_color_hex(0x1DCE6F), LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_opa(ui_BTNCancelContinue, 255, LV_PART_MAIN | LV_STATE_USER_4);

    ui_Label5 = lv_label_create(ui_BTNCancelContinue);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -2);
    lv_obj_set_y(ui_Label5, 2);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "NO");

    ui_BTNContinue = lv_btn_create(ui_ContinueScreen);
    lv_obj_set_width(ui_BTNContinue, 114);
    lv_obj_set_height(ui_BTNContinue, 44);
    lv_obj_set_x(ui_BTNContinue, 83);
    lv_obj_set_y(ui_BTNContinue, 72);
    lv_obj_set_align(ui_BTNContinue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNContinue, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTNContinue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTNContinue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTNContinue, lv_color_hex(0x00D804), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNContinue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTNContinue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTNContinue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BTNContinue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BTNContinue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_BTNContinue);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -2);
    lv_obj_set_y(ui_Label4, 2);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "YES");

    ui_SPLoading = lv_spinner_create(ui_ContinueScreen, 1000, 90);
    lv_obj_set_width(ui_SPLoading, 100);
    lv_obj_set_height(ui_SPLoading, 100);
    lv_obj_set_x(ui_SPLoading, -6);
    lv_obj_set_y(ui_SPLoading, 8);
    lv_obj_set_align(ui_SPLoading, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SPLoading, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SPLoading, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_LLoading = lv_label_create(ui_ContinueScreen);
    lv_obj_set_width(ui_LLoading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LLoading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LLoading, -9);
    lv_obj_set_y(ui_LLoading, -82);
    lv_obj_set_align(ui_LLoading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LLoading, "Loading");
    lv_obj_add_flag(ui_LLoading, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LLoading, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LLoading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LLoading, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTNCancelContinue, ui_event_BTNCancelContinue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNContinue, ui_event_BTNContinue, LV_EVENT_ALL, NULL);

}
