// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: CabelCaUI1


#include "UI/ui.h"

void ui_EStopScreen_screen_init(void)
{
    ui_EStopScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_EStopScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EStopScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EStopScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_EStopScreen);
    lv_obj_set_width(ui_Button1, 400);
    lv_obj_set_height(ui_Button1, 400);
    lv_obj_set_x(ui_Button1, -2);
    lv_obj_set_y(ui_Button1, 1);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EStopLabel = lv_label_create(ui_EStopScreen);
    lv_obj_set_width(ui_EStopLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EStopLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EStopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EStopLabel, "Press  to disable \nemergency stop");
    lv_obj_set_style_text_color(ui_EStopLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EStopLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EStopLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
