// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: CabelCaUI1

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MainScreen, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MainScreen, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MainScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MainScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc1 = lv_arc_create(ui_MainScreen);
lv_obj_set_width( ui_Arc1, 465);
lv_obj_set_height( ui_Arc1, 465);
lv_obj_set_x( ui_Arc1, 0 );
lv_obj_set_y( ui_Arc1, -5 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_Arc1, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_Arc1, 10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SLBatCC = lv_slider_create(ui_MainScreen);
lv_slider_set_value( ui_SLBatCC, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SLBatCC)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SLBatCC, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SLBatCC, 97);
lv_obj_set_height( ui_SLBatCC, 29);
lv_obj_set_x( ui_SLBatCC, 87 );
lv_obj_set_y( ui_SLBatCC, -139 );
lv_obj_set_align( ui_SLBatCC, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SLBatCC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SLBatCC, lv_color_hex(0xA4A4A4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SLBatCC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SLBatCC, lv_color_hex(0x1DF624), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SLBatCC, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SLBatCC, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SLBatCC, lv_color_hex(0x0BF416), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SLBatCC, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SLBatCC, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SLBatCC, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SLBatCC, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SLBatCC, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 84 );
lv_obj_set_y( ui_Label1, -165 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"BAT CC");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SLBatRC = lv_slider_create(ui_MainScreen);
lv_slider_set_value( ui_SLBatRC, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SLBatRC)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SLBatRC, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SLBatRC, 97);
lv_obj_set_height( ui_SLBatRC, 29);
lv_obj_set_x( ui_SLBatRC, -65 );
lv_obj_set_y( ui_SLBatRC, -140 );
lv_obj_set_align( ui_SLBatRC, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SLBatRC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SLBatRC, lv_color_hex(0xA4A4A4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SLBatRC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SLBatRC, lv_color_hex(0x1DF624), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SLBatRC, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SLBatRC, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SLBatRC, lv_color_hex(0x0BF416), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SLBatRC, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SLBatRC, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SLBatRC, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SLBatRC, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SLBatRC, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -70 );
lv_obj_set_y( ui_Label2, -166 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"BAT RC");
lv_label_set_recolor(ui_Label2,"true");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedValue = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_SpeedValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedValue, -64 );
lv_obj_set_y( ui_SpeedValue, -15 );
lv_obj_set_align( ui_SpeedValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedValue,"45");
lv_obj_set_style_text_color(ui_SpeedValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedValue, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedUnit = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_SpeedUnit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedUnit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedUnit, 29 );
lv_obj_set_y( ui_SpeedUnit, -15 );
lv_obj_set_align( ui_SpeedUnit, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedUnit,"Km/h");
lv_obj_set_style_text_color(ui_SpeedUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedUnit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedUnit, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ProfileLabel = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_ProfileLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ProfileLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ProfileLabel, -55 );
lv_obj_set_y( ui_ProfileLabel, 22 );
lv_obj_set_align( ui_ProfileLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ProfileLabel,"Profile: ");
lv_obj_set_style_text_color(ui_ProfileLabel, lv_color_hex(0xE1D9D9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ProfileLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ProfileLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ProfileNR = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_ProfileNR, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ProfileNR, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ProfileNR, -15 );
lv_obj_set_y( ui_ProfileNR, 23 );
lv_obj_set_align( ui_ProfileNR, LV_ALIGN_CENTER );
lv_label_set_text(ui_ProfileNR,"1");
lv_obj_set_style_text_color(ui_ProfileNR, lv_color_hex(0xE1D9D9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ProfileNR, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ProfileNR, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

}
