// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: CabelCaUI1

#include "../ui.h"

void ui_MoreScreen_screen_init(void)
{
ui_MoreScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MoreScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MoreScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MoreScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LSettingsOU = lv_label_create(ui_MoreScreen);
lv_obj_set_width( ui_LSettingsOU, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LSettingsOU, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LSettingsOU, 1 );
lv_obj_set_y( ui_LSettingsOU, -179 );
lv_obj_set_align( ui_LSettingsOU, LV_ALIGN_CENTER );
lv_label_set_text(ui_LSettingsOU,"More");
lv_obj_set_style_text_color(ui_LSettingsOU, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LSettingsOU, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LSettingsOU, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LGimbalS = lv_label_create(ui_MoreScreen);
lv_obj_set_width( ui_LGimbalS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LGimbalS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LGimbalS, -62 );
lv_obj_set_y( ui_LGimbalS, -115 );
lv_obj_set_align( ui_LGimbalS, LV_ALIGN_CENTER );
lv_label_set_text(ui_LGimbalS,"Gimbal: ");
lv_obj_set_style_text_color(ui_LGimbalS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LGimbalS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LGimbalS, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown2 = lv_dropdown_create(ui_MoreScreen);
lv_dropdown_set_options( ui_Dropdown2, "DJI\nOther" );
lv_obj_set_width( ui_Dropdown2, 109);
lv_obj_set_height( ui_Dropdown2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dropdown2, 52 );
lv_obj_set_y( ui_Dropdown2, -114 );
lv_obj_set_align( ui_Dropdown2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_pad_left(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_Dropdown2, &lv_font_montserrat_16, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown2), &lv_font_montserrat_10,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown2), &lv_font_montserrat_10,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_LOtherRope = lv_label_create(ui_MoreScreen);
lv_obj_set_width( ui_LOtherRope, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LOtherRope, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LOtherRope, -80 );
lv_obj_set_y( ui_LOtherRope, -73 );
lv_obj_set_align( ui_LOtherRope, LV_ALIGN_CENTER );
lv_label_set_text(ui_LOtherRope,"Other rope: ");
lv_obj_set_style_text_color(ui_LOtherRope, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LOtherRope, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LOtherRope, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch2 = lv_switch_create(ui_MoreScreen);
lv_obj_set_width( ui_Switch2, 50);
lv_obj_set_height( ui_Switch2, 25);
lv_obj_set_x( ui_Switch2, 26 );
lv_obj_set_y( ui_Switch2, -75 );
lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );


ui_SLRopeL = lv_slider_create(ui_MoreScreen);
lv_slider_set_range(ui_SLRopeL, 0,1000);
lv_slider_set_mode(ui_SLRopeL, LV_SLIDER_MODE_SYMMETRICAL);
lv_slider_set_value( ui_SLRopeL, 2, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SLRopeL)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SLRopeL, 20, LV_ANIM_OFF);
lv_obj_set_width( ui_SLRopeL, 354);
lv_obj_set_height( ui_SLRopeL, 11);
lv_obj_set_x( ui_SLRopeL, -14 );
lv_obj_set_y( ui_SLRopeL, -11 );
lv_obj_set_align( ui_SLRopeL, LV_ALIGN_CENTER );


ui_LStoplenght = lv_label_create(ui_MoreScreen);
lv_obj_set_width( ui_LStoplenght, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LStoplenght, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LStoplenght, -9 );
lv_obj_set_y( ui_LStoplenght, 56 );
lv_obj_set_align( ui_LStoplenght, LV_ALIGN_CENTER );
lv_label_set_text(ui_LStoplenght,"Break activation distance: ");
lv_obj_set_style_text_color(ui_LStoplenght, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LStoplenght, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LStoplenght, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LStoplenghtV = lv_label_create(ui_MoreScreen);
lv_obj_set_width( ui_LStoplenghtV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LStoplenghtV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LStoplenghtV, -8 );
lv_obj_set_y( ui_LStoplenghtV, 105 );
lv_obj_set_align( ui_LStoplenghtV, LV_ALIGN_CENTER );
lv_label_set_text(ui_LStoplenghtV,"2m");
lv_obj_set_style_text_color(ui_LStoplenghtV, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LStoplenghtV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LStoplenghtV, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTNBackMore = lv_btn_create(ui_MoreScreen);
lv_obj_set_width( ui_BTNBackMore, 114);
lv_obj_set_height( ui_BTNBackMore, 44);
lv_obj_set_x( ui_BTNBackMore, 1 );
lv_obj_set_y( ui_BTNBackMore, 164 );
lv_obj_set_align( ui_BTNBackMore, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTNBackMore, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTNBackMore, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTNBackMore, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTNBackMore, lv_color_hex(0x1F60EA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTNBackMore, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_BTNBackMore, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BTNBackMore, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BTNBackMore, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BTNBackMore, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_L_Back_MS = lv_label_create(ui_BTNBackMore);
lv_obj_set_width( ui_L_Back_MS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_L_Back_MS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_L_Back_MS, -2 );
lv_obj_set_y( ui_L_Back_MS, 2 );
lv_obj_set_align( ui_L_Back_MS, LV_ALIGN_CENTER );
lv_label_set_text(ui_L_Back_MS,"Back");

ui_LRopeLenghV = lv_label_create(ui_MoreScreen);
lv_obj_set_width( ui_LRopeLenghV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LRopeLenghV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LRopeLenghV, -10 );
lv_obj_set_y( ui_LRopeLenghV, 13 );
lv_obj_set_align( ui_LRopeLenghV, LV_ALIGN_CENTER );
lv_label_set_text(ui_LRopeLenghV,"0m");
lv_obj_set_style_text_color(ui_LRopeLenghV, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LRopeLenghV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LRopeLenghV, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LRopeLengh = lv_label_create(ui_MoreScreen);
lv_obj_set_width( ui_LRopeLengh, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LRopeLengh, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LRopeLengh, -6 );
lv_obj_set_y( ui_LRopeLengh, -33 );
lv_obj_set_align( ui_LRopeLengh, LV_ALIGN_CENTER );
lv_label_set_text(ui_LRopeLengh,"Rope length: ");
lv_obj_set_style_text_color(ui_LRopeLengh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LRopeLengh, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LRopeLengh, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SLRopeSL = lv_slider_create(ui_MoreScreen);
lv_slider_set_range(ui_SLRopeSL, 2,6);
lv_slider_set_mode(ui_SLRopeSL, LV_SLIDER_MODE_SYMMETRICAL);
lv_slider_set_value( ui_SLRopeSL, 2, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SLRopeSL)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SLRopeSL, 20, LV_ANIM_OFF);
lv_obj_set_width( ui_SLRopeSL, 354);
lv_obj_set_height( ui_SLRopeSL, 11);
lv_obj_set_x( ui_SLRopeSL, -11 );
lv_obj_set_y( ui_SLRopeSL, 81 );
lv_obj_set_align( ui_SLRopeSL, LV_ALIGN_CENTER );


lv_obj_add_event_cb(ui_SLRopeL, ui_event_SLRopeL, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTNBackMore, ui_event_BTNBackMore, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SLRopeSL, ui_event_SLRopeSL, LV_EVENT_ALL, NULL);

}
