// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: CabelCaUI1

#include "../ui.h"

void ui_SettingsScreen_screen_init(void)
{
ui_SettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_SettingsScreen, LV_SCROLLBAR_MODE_ON);
lv_obj_set_style_radius(ui_SettingsScreen, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LSettingsU = lv_label_create(ui_SettingsScreen);
lv_obj_set_width( ui_LSettingsU, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LSettingsU, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LSettingsU, 1 );
lv_obj_set_y( ui_LSettingsU, -183 );
lv_obj_set_align( ui_LSettingsU, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_LSettingsU,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_LSettingsU, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_LSettingsU,"Settings");
lv_obj_set_style_text_color(ui_LSettingsU, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LSettingsU, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LSettingsU, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller2 = lv_roller_create(ui_SettingsScreen);
lv_roller_set_options( ui_Roller2, "Profill \nInfo\nBluethooth\nUpdate\nReset", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller2, 122);
lv_obj_set_width( ui_Roller2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller2, -4 );
lv_obj_set_y( ui_Roller2, -26 );
lv_obj_set_align( ui_Roller2, LV_ALIGN_CENTER );

ui_BTN_GoTo = lv_btn_create(ui_SettingsScreen);
lv_obj_set_width( ui_BTN_GoTo, 114);
lv_obj_set_height( ui_BTN_GoTo, 44);
lv_obj_set_x( ui_BTN_GoTo, -6 );
lv_obj_set_y( ui_BTN_GoTo, 96 );
lv_obj_set_align( ui_BTN_GoTo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_GoTo, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTN_GoTo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_GoTo, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_GoTo, lv_color_hex(0x00D804), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_GoTo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_BTN_GoTo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BTN_GoTo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BTN_GoTo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BTN_GoTo, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_L_GoTo_SS = lv_label_create(ui_BTN_GoTo);
lv_obj_set_width( ui_L_GoTo_SS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_L_GoTo_SS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_L_GoTo_SS, -2 );
lv_obj_set_y( ui_L_GoTo_SS, 2 );
lv_obj_set_align( ui_L_GoTo_SS, LV_ALIGN_CENTER );
lv_label_set_text(ui_L_GoTo_SS,"Go To ");

lv_obj_add_event_cb(ui_Roller2, ui_event_Roller2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_GoTo, ui_event_BTN_GoTo, LV_EVENT_ALL, NULL);

}
